name: Trigger Jenkins Build

on:
  push:
    branches:
      - main  

jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_jivah_URL }} 
          JENKINS_JOB: ${{ secrets.JENKINS_jivah_DEV_JOB_NAME }} 
          JENKINS_USER: ${{ secrets.JENKINS_jivah_USER }} 
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_jivah_TOKEN }}  
        run: |
          curl -X POST "$JENKINS_URL/job/$JENKINS_JOB/build" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN" \
            --header "Content-Type: application/json"
